### ISSUE TITLE
Progressive loading broken

### ISSUE THREAD

**Issue by sanderpick** [textileio/textile-mobile#898] opened 2019-02-03 17:16 UTC
I often see an white / blank photo before the actual pixels arrive. Sometime it takes 5-10s for the photo so show... I think we used to show the thumb while loading the higher res, no?

**Comment by sanderpick** [comment] 2019-03-04 21:38
Think we could tackle this one in Sprint 7?

**Comment by andrewxhill** [comment] 2019-03-05 09:59
i had thrown this in slack so it got lost, but if any of you can add some color off the top of your heads to the early ones

1. are we still using progressive image in the image feed?
2. i notice the image appears as a thumb (on the previous screen) even if the white screen remains, is 100 not small enough? (just need to look at schema, what are the image sizes of media schema)
3. is 100 being processed still correctly in the go request? (edited) 
4. is something broken about the stacking or refreshing of the component

**Comment by andrewxhill** [comment] 2019-03-05 10:44
~~are we still using progressive image in the image feed?~~

this looks good

https://github.com/textileio/textile-mobile/blob/master/App/Components/photo.tsx

**Comment by andrewxhill** [comment] 2019-03-05 10:58
~~i notice the image appears as a thumb (on the previous screen) even if the white screen remains, is 100 not small enough? (just need to look at schema, what are the image sizes of media schema)~~

ProgressiveImage is trying to get a preview with width == 100: https://github.com/textileio/textile-mobile/blob/master/App/Components/ProgressiveImage.tsx#L34

Media Schema has a thumbnail with width === 100: https://github.com/textileio/go-textile/blob/master/schema/textile/media.go#L29

Boom... okay, if I'm reading this right, here is where it fails

`imgs[i].width < imgs[j].width`

https://github.com/textileio/go-textile/blob/master/mobile/files.go#L330

I think that's actually wrong, if I am getting an image with minimum width of 100, I'd expect an image of 100 is okay. Unless there is some other step that means maybe 100 isn't 100. But yeah, we should just change that to <= 100

**Comment by andrewxhill** [comment] 2019-03-05 11:21
Okay, quick new test before digging into the component. Tossed a breakpoint here,

https://github.com/textileio/textile-mobile/blob/master/ios/NativeViews/TextileImageView.m#L41

And on loading the feed of a group with a single image in it, I saw the requests,

- `forMinWidth=72` pretty sure that's the avatar in upper right
- `forMinWidth=1125` that must be the full width image in the group
- `forMinWidth=300` that must be the smaller preview

So... I'm thinking 100 in RN world is being translated for a 3x pixel density or something before it makes it to the native image request. digging moe

**Comment by andrewxhill** [comment] 2019-03-05 11:26
Ah... there it is,

https://github.com/textileio/textile-mobile/blob/master/App/Components/TextileImage.tsx#L38

TextileImage is overriding the requested width, never seen that before. Simple fix, let me know what you think about these @asutula 

1. Are we going to get the independent image module merged? We can then move the fix over to there.
2. Should we make an optional way to override the PixelRatio stuff when using TextileImage, or
3. Should we remove it totally and leave it up to the caller to take care of

**Comment by andrewxhill** [comment] 2019-03-05 11:32
or, we could simply change the min width call in progressiveimage to 30 and let it go for now if neither of those sound right

**Comment by sanderpick** [comment] 2019-03-05 17:12
Nice! Added to Sprint 7

**Comment by asutula** [comment] 2019-03-05 18:28
Just making sure I understand what you think the problem is....

It makes sense to me that `TextileImage` should multiply the width based on the pixel density of the screen. 

Why would this cause a problem? What's wrong with asking for a `forMinWidth` of `300`? Shouldn't that work?

> Comparison looks okay, so thumbnail of width 100 should be returned when asking for the image with minWidth of 100,

No, it should return an image suitable for 300 so it looks nice a crisp on the screen.

**Comment by andrewxhill** [comment] 2019-03-05 18:33
No no not in this case. In this case i'm making an explicit request for an image of 100 because it's a low res placeholder until the nice and crisp one shows up later. So yeah... progressive image wants 100 it says 100, but when it says anything higher it wants what the platform says. See?

**Comment by asutula** [comment] 2019-03-05 18:34
Oh, then you should ask for some tiny size, like 10 or 30 or whatever

**Comment by asutula** [comment] 2019-03-05 18:35
Like you suggested.

**Comment by sanderpick** [comment] 2019-03-17 15:56
This one done?

**Comment by andrewxhill** [comment] 2019-03-17 17:09
just gotta merge, will do now
https://github.com/textileio/textile-mobile/pull/949

**Closed by andrewxhill** 2019-03-17 17:09 UTC
Labels: bug

**Comment by sanderpick** [comment] 2019-03-18 16:44
Sweet!
